### ISSUE TITLE
'IDialogContext' does not contain a definition for 'Done'

### ISSUE THREAD

**Issue by taranais** [CXuesong/BotBuilder.Standard#4]
## Bot Info 
* SDK Platform: .NET 
* SDK Version:  CXuesong.Ported.Microsoft.Bot.Builder 3.12.2.5
* Active Channels: emulator
* Deployment Environment: localhost

## Issue Description
'Microsoft.Bot.Builder.Dialogs.IDialogContext' does not contain a definition for 'Done'

## Code Example
       public Task StartAsync(IDialogContext context)
        {
            context.PostAsync($"[CatalogDialog] I am the Catalog dialog.");
            context.Call(new CatalogFilterDialog(), ExecutedCatalogFilterAsync);
            return Task.CompletedTask;
        }
      private async  Task ExecutedCatalogFilterAsync(IDialogContext context, IAwaitable<CatalogFilter> result)
        {
            var catalogFilter = await result;          /// <-- Excpetion throw here
            context.Wait(MessageReceivedAsync);
        }

      public class CatalogDialog : IDialog<object>
      {
           [...]
           context.Done(filter);
           [...]
      }

## Expected Behavior
      retrieve filter object on ExecutedCatalogFilterAsync

## Actual Results
Exception: 'Microsoft.Bot.Builder.Dialogs.IDialogContext' does not contain a definition for 'Done'

**Comment by CXuesong** [comment]
What's your version of `CXuesong.Ported.Microsoft.Bot.Connector` package? Have you explicitly referenced the latest pre-release?

**Comment by taranais** [comment]
from .csproj

    <PackageReference Include="CXuesong.Ported.Microsoft.Bot.Builder" Version="3.12.2.5" />
    <PackageReference Include="CXuesong.Ported.Microsoft.Bot.Connector" Version="3.12.2.6-int0" />
    <PackageReference Include="CXuesong.Ported.Microsoft.Bot.Builder.Autofac" Version="3.12.2.5" />

**Comment by CXuesong** [comment]
Uhmm, that's wierd. Did you refer to the same packages of different version across different projects, perhaps by accident?

I'm using the following references (the same as yours) and it works well
```xml
    <PackageReference Include="CXuesong.Ported.Microsoft.Bot.Builder" Version="3.12.2.5" />
    <PackageReference Include="CXuesong.Ported.Microsoft.Bot.Builder.Autofac" Version="3.12.2.5" />
    <PackageReference Include="CXuesong.Ported.Microsoft.Bot.Connector" Version="3.12.2.6-int0" />
```

**Comment by taranais** [comment]
Filter was a dynamic type object. I set filter to a class and it now works.

**Comment by CXuesong** [comment]
Glad to hear that. Enjoy building bots!

**Comment by luccasmf** [comment]
@CXuesong I'm using your ported libraries but could not make bot work when I plublish it on Azure ... I think the authentication is not working properly ... I had to use the deprecated Connector, because the new one shows me a reference error I couldn't solve ... could you help me ?

**Comment by CXuesong** [comment]
@luccasmf Sure. What is the reference error the IDE tells you?

**Comment by luccasmf** [comment]
When I try to install your newest connector package, it just shows me that I can't install... 

When I try to use the Microsoft new connector (for net core 2.0) , the int shows me an error that ICredentialProvider exists on both DLL ... (CS0433)..

independent of the package that I use, it works locally, bu when hosted to Azure, don't

**Comment by CXuesong** [comment]
May I take a look at your csproj file, especially, the `PackageReference` elements? If you are using my ported packages, then you need to remove ALL the references to MS's official BotBuilder packages.

**Comment by luccasmf** [comment]
```
  <PackageReference Include="Autofac" Version="4.6.2" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="4.2.0" />
    <PackageReference Include="CXuesong.Ported.Microsoft.Bot.Builder" Version="3.12.2.5" />
    <PackageReference Include="CXuesong.Ported.Microsoft.Bot.Builder.Autofac" Version="3.12.2.5" />
    <PackageReference Include="Microsoft.AdaptiveCards" Version="0.5.1" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Microsoft.Bot.Connector.AspNetCore" Version="2.0.0.3" />
```
Wich ones I remove ?

**Comment by CXuesong** [comment]
Removing `Microsoft.Bot.Connector.AspNetCore` should solve the problem.
As for the authentication problem, you may try to explicitly install CXuesong.Ported.Microsoft.Bot.Connector v3.12.2.6-int0.

**Comment by luccasmf** [comment]
I can't install CXuesong.Ported.Microsoft.Bot.Connector  packet via nuget pack... it fails and rolls back ... do you have this last version on Nuget ou Bower ?

**Comment by luccasmf** [comment]
Man, I added your packages and it has worked locally... but When I add the [Authentication(Role="bot")] in the controller and publish the bot, the channel I had created on azure can't connect ... i double checked the key and app id ... but still not working ... damn it

**Comment by luccasmf** [comment]
Even checking the app id and key of the channel I had created, it is not communicating ...  

My "Startup.cs":
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton(_ => Configuration);

            var credentialProvider = new StaticCredentialProvider(
                Configuration.GetSection(MicrosoftAppCredentials.MicrosoftAppIdKey)?.Value,
                Configuration.GetSection(MicrosoftAppCredentials.MicrosoftAppPasswordKey)?.Value);

            services.AddAuthentication(
                     // This can be removed after https://github.com/aspnet/IISIntegration/issues/371
                     options =>
                     {
                         options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                         options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                     }
                 )
                 .AddBotAuthentication(credentialProvider);

            services.AddSingleton(typeof(ICredentialProvider), credentialProvider);

            services.AddMvc(options =>
            {
                options.Filters.Add(typeof(TrustServiceUrlAttribute));
            });
            services.AddMvc();

        }
```

My Controller:
```
[Authorize(Roles = "Bot")] // I tried to let just the [Authorize]
        [HttpPost]
        public async Task<OkResult> Post([FromBody]Activity activity)
        {           

            if (activity.Type == ActivityTypes.Message)
            {
                await Conversation.SendAsync(activity, () => new Dialogs.RootDialog());
            }
            else
            {
                HandleSystemMessage(activity);
            }
           // var response = new HttpResponseMessage(HttpStatusCode.OK);//Request.CreateResponse(HttpStatusCode.OK);
            return Ok();
        }
```

**Comment by CXuesong** [comment]
Uhmm, with my ported library, your controller code should be similar to that in classical ASP.NET, that is, to use `BotAuthenticationAttribute` instead of `AuthorizeAttribute`. In addition, you need to call `SettingsUtils.AttachConfiguration` on initialization of the website. Please take a look at .NET Core example in this repository, or [`CXuesong/BotBuilderPlayground.Standard`](https://github.com/CXuesong/BotBuilderPlayground.Standard) for a clean start-up template on this.

p.s.

If you still cannot resolve the problem, please start a new issue and we can continue the discussion there 😄

**Comment by luccasmf** [comment]
Solved, thanks Bro
